version: '3'
services:
  back:
    build:
      context: ./back
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./back:/app
      - static:/app/static
      - media:/app/media
    depends_on:
      - db
    restart: always
    networks:
      - union-network 

  server:
    build:
      context: ./nginx
    volumes:
      - static:/app/static
      - media:/app/media
    ports:
      - 80:8000
    depends_on:
      - back
      - front
    restart: always
    networks:
      - union-network 

  front:
    build:
      context: ./front_app
    depends_on:
      - back
    restart: always
    networks:
      - union-network 


  db:
    image: postgres:12.0-alpine
    volumes:
      - ./bot:/bot
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
      - POSTGRES_DB=django_db
    networks:
      - union-network


volumes:
  postgres_volume:
  static:
  media:

networks:
  union-network:
