# Generated by Django 4.0 on 2022-01-16 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Описание файла/картинки и тд.')),
                ('photo', models.ImageField(blank=True, default='', upload_to='carousel', verbose_name='Задний фон')),
            ],
            options={
                'verbose_name': 'Файлы',
                'verbose_name_plural': 'Файлы',
            },
        ),
        migrations.CreateModel(
            name='MainCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Главный текст')),
                ('describe', models.TextField(verbose_name='Текст описания')),
                ('button_text', models.CharField(blank=True, max_length=200, verbose_name='Текст на кнопке')),
                ('button_url', models.CharField(blank=True, max_length=300, verbose_name='Ссылка на кнопке')),
                ('photo', models.ImageField(blank=True, default='', upload_to='carousel', verbose_name='Задний фон')),
            ],
            options={
                'verbose_name': 'Первая секция',
                'verbose_name_plural': 'Первая секция',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('email', models.TextField(verbose_name='Email')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('message', models.CharField(max_length=200, verbose_name='Сообщение')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='Время оставления заявки')),
            ],
            options={
                'verbose_name': 'Клиенты',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('describe', models.TextField(verbose_name='Текст описания работы')),
                ('files', models.ManyToManyField(related_name='product_files', to='main.Files', verbose_name='Прикрепленные файлы')),
            ],
            options={
                'verbose_name': 'Продукты',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='OurWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название работы')),
                ('describe', models.TextField(verbose_name='Текст описания работы')),
                ('button_url', models.CharField(blank=True, max_length=300, verbose_name='Ссылка')),
                ('files', models.ManyToManyField(related_name='work_files', to='main.Files', verbose_name='Прикрепленные файлы')),
            ],
            options={
                'verbose_name': 'Наши работы',
                'verbose_name_plural': 'Наши работы',
            },
        ),
        migrations.CreateModel(
            name='OurService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название работы')),
                ('describe', models.TextField(verbose_name='Текст описания работы')),
                ('button_url', models.CharField(blank=True, max_length=300, verbose_name='Ссылка')),
                ('files', models.ManyToManyField(related_name='service_files', to='main.Files', verbose_name='Прикрепленные файлы')),
            ],
            options={
                'verbose_name': 'Наши услуги',
                'verbose_name_plural': 'Наши услуги',
            },
        ),
    ]
