# Generated by Django 4.0 on 2022-01-27 12:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_support_email_alter_support_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sub_title',
            field=models.CharField(default='', max_length=200, verbose_name='Мелкое описание'),
        ),
        migrations.AlterField(
            model_name='products',
            name='describe',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Полный текст'),
        ),
    ]
