# Generated by Django 4.0 on 2022-01-27 17:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_products_sub_title_alter_products_describe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=200, verbose_name='Название страницы')),
                ('title', models.CharField(default='', max_length=200, verbose_name='Оглавление')),
                ('describe', ckeditor.fields.RichTextField(default='', verbose_name='Описание страницы')),
                ('files', models.ManyToManyField(related_name='page_files', to='main.Files', verbose_name='Прикрепленные файлы')),
            ],
            options={
                'verbose_name': 'Страницы',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
