# Generated by Django 4.0 on 2022-02-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='photo',
            field=models.FileField(blank=True, default='', upload_to='carousel', verbose_name='Карнтинка'),
        ),
        migrations.RemoveField(
            model_name='ourservice',
            name='files',
        ),
        migrations.AddField(
            model_name='ourservice',
            name='files',
            field=models.ImageField(blank=True, default='', upload_to='service', verbose_name='Картинка'),
        ),
        migrations.RemoveField(
            model_name='ourwork',
            name='files',
        ),
        migrations.AddField(
            model_name='ourwork',
            name='files',
            field=models.ImageField(blank=True, default='', upload_to='service', verbose_name='Картинка'),
        ),
    ]
