# Generated by Django 4.0 on 2022-02-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_files_photo_remove_ourservice_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourwork',
            name='files',
        ),
        migrations.AddField(
            model_name='ourwork',
            name='files',
            field=models.ManyToManyField(related_name='work_files', to='main.Files', verbose_name='Прикрепленные файлы'),
        ),
    ]
