# Generated by Django 4.0 on 2022-02-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_page_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='page_files', to='main.Files', verbose_name='Прикрепленные файлы'),
        ),
        migrations.AlterField(
            model_name='page',
            name='show',
            field=models.BooleanField(default=True, verbose_name='Не показывать в меню'),
        ),
        migrations.AlterField(
            model_name='products',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='product_files', to='main.Files', verbose_name='Прикрепленные файлы'),
        ),
    ]
