# Generated by Django 4.0 on 2022-02-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0003_alter_support_email_alter_support_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Главный текст')),
                ('describe', models.TextField(verbose_name='Текст описания')),
                ('button_text', models.CharField(blank=True, max_length=200, verbose_name='Текст на кнопке')),
                ('button_url', models.CharField(blank=True, max_length=300, verbose_name='Ссылка на кнопке')),
                ('photo', models.ImageField(blank=True, default='', upload_to='carousel', verbose_name='Задний фон')),
            ],
            options={
                'verbose_name': 'Первая секция',
                'verbose_name_plural': 'Первая секция',
            },
        ),
    ]
